import type { Metadata } from "next";
import Styles from './styles.module.css'
import Navbar from "../navbar/page";

export const metadata: Metadata = {
    title: "About Page",
    description: "Generated by CodeTechX",
};

export default function AboutLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <main className={Styles.main}>
                {children}
            </main>
        </>
    );
}
